### ISSUE TITLE
SIMPLE-TYPE-ERROR on ECL

### ISSUE THREAD

**Issue by no-defun-allowed** [marcoheisig/the-cost-of-nothing#1]
I tried to run a test suite that uses the-cost-of-nothing on Embeddable Common Lisp, and the tests failed with a simple-type-error. I don't really know how to use the ECL debugger, so I'm only able to get this much out of it:

```lisp
> (the-cost-of-nothing:bench (cons 1 1))

Condition of type: SIMPLE-TYPE-ERROR
The value of THE-COST-OF-NOTHING::QUANTITY is 7941909882354657538831/90918756469339491611189513286, which is not of type FLOAT.

Available restarts:

1. (STORE-VALUE) Supply a new value of THE-COST-OF-NOTHING::QUANTITY
2. (RESTART-TOPLEVEL) Go back to Top-Level REPL.

Broken at SI:BYTECODES. [Evaluation of: (THE-COST-OF-NOTHING:BENCH (CONS 1 1))] In: #<process TOP-LEVEL>.
>> :backtrace

Backtrace:
  > SI:BYTECODES [Evaluation of: (THE-COST-OF-NOTHING:BENCH (CONS 1 1))]
  > si:bytecodes [Evaluation of: (si:top-level t)]
```

I think this has to do with WRITE-SI-UNIT being fed a ratio instead of a float in BENCHMARK-THUNK. If I change the NUMBER-OF-SAMPLES in that to `0.0` from `0`, floating-point contagion applies and it works correctly.

**Comment by marcoheisig** [comment]
Fixed in f364029fbbf37ae5786f2f9ddf6185dd204a7185.  Thanks for reporting!
